name: 02 - Workflow Filtro

on:
  push:
    branches: 'feature/**' #Informa que o workflow deve ser disparado sempre que houver um push em branches que começam com feature/

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir o evento
        run: echo "Workflow disparado por ${{ github.event_name }}" #informa o tipo de evento (push)